services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - network

  minio:
    container_name: minio
    image: quay.io/minio/minio:latest
    restart: always
    environment:
      - MINIO_ROOT_USER=${S3_USER}
      - MINIO_ROOT_PASSWORD=${S3_PASSWORD}
    ports:
      - ${S3_PORT}:${S3_PORT}
      - ${S3_CONSOLE_PORT}:${S3_CONSOLE_PORT}
    command: minio server --console-address ":${S3_CONSOLE_PORT}" /data
    volumes:
      - minio_data:/data
    networks:
      - network

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - redis_data:/data
    networks:
      - network

volumes:
  postgres_data:
  minio_data:
  redis_data:

networks:
  network:
