/* DO NOT EDIT, file generated by nestjs-i18n */

 
/* prettier-ignore */
import { Path } from "nestjs-i18n";
/* prettier-ignore */
export type I18nTranslations = {
    "error": {
        "create_session": string;
        "delete_session": string;
        "existing_user_by_username": string;
        "existing_user_by_email": string;
        "existing_project_by_title": string;
        "user_not_found": string;
        "users_not_found": string;
        "project_not_found": string;
        "project_is_archived": string;
        "file_not_found": string;
        "task_not_found": string;
        "user_dont_have_access": string;
        "owner_cannot_be_member": string;
        "invalid_password": string;
    };
    "validation": {
        "min_lenght": string;
        "max_langth": string;
    };
};
/* prettier-ignore */
export type I18nPath = Path<I18nTranslations>;
