/* DO NOT EDIT, file generated by nestjs-i18n */

 
/* prettier-ignore */
import { Path } from "nestjs-i18n";
/* prettier-ignore */
export type I18nTranslations = {
    "error": {
        "create_session": string;
        "delete_session": string;
        "existing_user_by_username": string;
        "existing_user_by_email": string;
        "user_not_found": string;
        "invalid_password": string;
    };
    "validation": {
        "min_lenght": string;
        "max_langth": string;
    };
};
/* prettier-ignore */
export type I18nPath = Path<I18nTranslations>;
